webservice:
  host: '0.0.0.0'
  port: '5000'
  debug: True
redis:
  host: 'redis'
  port: 6379
  db: 0
data_stream:
  data_queue: "data_queue"
  batch_size: 32
  server_sleep: 0.25
  client_sleep: 0.25
model:
  pathdir: "./model/"


